apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: minio-deployment
spec:
  selector:
    matchLabels:
      app: minio # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: minio
    spec:
      # Refer to the secret created earlier
      volumes:
      - name: minio-gcs-credentials
        secret:
          # Name of the Secret created earlier
          secretName: minio-gcs-credentials
      containers:
      - name: minio
        # Pulls the default Minio image from Docker Hub
        image: minio/minio:RELEASE.2020-01-16T22-40-29Z
        args:
        - gateway
        - gcs
        envFrom:
          - secretRef:
              name: minio-secret
        env:
        # Minio secert and access key is created by terraform
        # Google Cloud Service uses this variable
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/credentials/minio_gcs_credentials.json"
        ports:
        - containerPort: 9000
        # Mount the volume into the pod
        # Credentials are created by terraform
        volumeMounts:
        - name: minio-gcs-credentials
          mountPath: "/etc/credentials"
          readOnly: true
