apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# needs defining namespace in the bash script -> not with kustomization
# or a newer version of kustomize with chartinflator plugin
- ./namespace.yaml
- ./nginx-controller.yaml