apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-gateway

bases:
  - ./../../docker/base
  - ../../ambassador/overlays/esp

resources:
  - namespace.yaml

secretGenerator:
  - files:
      - key.json=./google-creds-secret.json
    name: google-cloud-creds
    type: Opaque
