apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: gcr-docker-cfg-eu
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=docker_config.json
