apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metacontroller

bases:
  - github.com/GoogleCloudPlatform/metacontroller
  - danisla-cloud-endpoints-controller

patchesStrategicMerge:
  - ce-controller-admin-patch.yaml

resources:
  - namespace.yaml

patchesJson6902:
  - target:
      group: metacontroller.k8s.io
      version: v1alpha1
      kind: CompositeController
      name: cloud-endpoints-controller
    path: ./ce-controller-patch.yaml

images:
  - name: gcr.io/cloud-solutions-group/cloud-endpoints-controller
    newTag: 0.2.1
