apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# below not working in kustomize 2.x < 3.0
namespace: api-gateway
namePrefix: api-gateway-

resources:
  - ambassador-rbac.yaml

patchesJson6902:
  - path: svc-module-json-patch.yaml
    target:
      version: v1
      kind: Service
      name: ambassador
      namespace: default

configMapGenerator:
  - name: ambassador-config
    literals:
      - AMBASSADOR_ID="api-gateway"
