apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-commander
  name: redis-commander
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: redis-commander
  type: NodePort