apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsenrypt-cert-issuer
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: info@dev.com
        privateKeySecretRef:
          name: letsenrypt-cert-issuer
        http01: {}
