apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsenrypt-cert-issuer
spec:
    acme:
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        # FIX ME
        email: info@dev.com
        privateKeySecretRef:
          name: letsenrypt-cert-issuer
        http01: {}
