---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador
rules:
  - apiGroups: [""]
    resources: ["endpoints", "namespaces", "secrets", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["getambassador.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]