apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      name: rest
      protocol: TCP
    - port: 9300
      targetPort: 9300
      name: nodes
      protocol: TCP
  selector:
    app: elasticsearch
