- op: replace
  path: /spec/destinations/0/server
  value: "https://{cluster-ip}"
- op: replace
  path: /spec/destinations/1/server
  value: "https://{cluster-ip}"
- op: replace
  path: /spec/destinations/2/server
  value: "https://{cluster-ip}"
- op: replace
  path: /spec/destinations/3/server
  value: "https://{cluster-ip}"
- op: replace
  path: /spec/destinations/4/server
  value: "https://{cluster-ip}"
- op: replace
  path: /spec/destinations/5/server
  value: "https://{cluster-ip}"
- op: replace
  path: /spec/destinations/6/server
  value: "https://{cluster-ip}"
- op: replace
  path: /spec/destinations/7/server
  value: "https://{cluster-ip}"
- op: replace
  path: /spec/destinations/8/server
  value: "https://{cluster-ip}"
- op: replace
  path: /spec/destinations/9/server
  value: "https://{cluster-ip}"
- op: replace
  path: /spec/destinations/10/server
  value: "https://{cluster-ip}"
- op: replace
  path: /spec/destinations/11/server
  value: "https://{cluster-ip}"