apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# for cluster-wide ingress
# namespace: nginx-controller

bases:
  - ../../bases

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: nginx-ingress-controller
    path: ./nginx-controller-ip-patch.yaml
  - target:
      version: v1
      kind: Service
      name: nginx-ingress-default-backend
    path: ./nginx-backend-clusterip-patch.yaml
