apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: esp-gateway

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: esp-config
    literals:
      - BACKEND_HOST="ambassador"
      - BACKEND_PORT="80"
