apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ambassador-v0.yaml
  - ambassador-rbac.yaml

# https://github.com/kubeflow/manifests/tree/master/common/ambassador/base
vars:
- name: ambassadorServiceAccount
  objref:
    kind: ConfigMap
    name: ambassador-config
    apiVersion: v1
  fieldref:
    fieldpath: data.ambassadorServiceAccount

configurations:
- params.yaml

configMapGenerator:
  - name: ambassador-config
    literals:
      - ambassadorServiceAccount="TODO"