apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metacontroller

bases:
  - ../../base

secretGenerator:
  - files:
      - key.json=./endpoints-admin-secret.json
    name: endpoints-admin-creds
    type: Opaque
